import Head from "next/head";
import { Box, Container, Heading, SlideFade } from "@chakra-ui/react";
import Paragraph from "../components/Paragraph";
import { useState } from "react";

const Blog = () => {
  return (
    <div>
      <Head>
        <title>Blog | Nathanael Louzoun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.md" mt={10}>
          <SlideFade in={true} offsetY={80}>
            <Box>
              <Heading
                as="h1"
                fontSize={{ base: "28px", md: "32px", lg: "36px" }}
                mb={4}
              >
                Blog
              </Heading>
              <Paragraph fontSize="xl" lineHeight={1.6}>
                Blog list
              </Paragraph>
            </Box>
          </SlideFade>
        </Container>
      </main>
    </div>
  );
};

export default Blog;
