import Head from "next/head";
import {
  Box,
  Container,
  Heading,
  SlideFade,
  Divider,
  Avatar,
  Center,
} from "@chakra-ui/react";

import Paragraph from "../components/Paragraph";
import Company from "../components/pages/Company";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nathanael Louzoun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.md" mt={10}>
          <SlideFade in={true} offsetY={80}>
            <Box>
              <Center>
                <Avatar
                  mb={8}
                  size="2xl"
                  name="Nathanael Louzoun"
                  src="https://pbs.twimg.com/profile_images/1472278998625443852/tid81uzr_400x400.jpg"
                />
              </Center>

              <Heading
                as="h1"
                fontSize={{ base: "28px", md: "40px", lg: "48px" }}
                my={3}
              >
                Hey , I’m Nathanael Louzoun
              </Heading>
              <Paragraph fontSize="2xl" lineHeight={1.6}>
                I’m a front end developer, who is focused on React and Angular.
                I’m born in Paris. I’ve studied at Hetic and I’m now working
                fulltime at DessIA. In my spare time, I’m contributing to open
                source projects I used on a daily basis.
              </Paragraph>
              <Divider my={10} />
            </Box>
          </SlideFade>
          <Company />
        </Container>
      </main>
    </div>
  );
}
